CREATE TABLE SUBSCRIPTION(id VARCHAR(64) PRIMARY KEY, user VARCHAR(1023) NOT NULL, contact VARCHAR(2047) NOT NULL, name VARCHAR(128), state VARCHAR(20) NOT NULL, groups VARCHAR(2000));
CREATE INDEX INDEX_SUBSCRIPTION_USER ON SUBSCRIPTION (user);
CREATE UNIQUE INDEX UNIQUE_INDEX_SUBSCRIPTION_USER_CONTACT ON SUBSCRIPTION (user, contact);

CREATE TABLE SUBSCRIPTION_NOTIFICATION (id VARCHAR(64) PRIMARY KEY, user VARCHAR(1023) NOT NULL, contact VARCHAR(2047) NOT NULL, subscription_type VARCHAR(12) NOT NULL, CONSTRAINT UNIQUE_USER_CONTACT_SUBSCRIPTION_TYPE UNIQUE (user, contact, subscription_type));
CREATE INDEX INDEX_SUBSCRIPTION_NOTIFICATION_USER_CONTACT ON SUBSCRIPTION_NOTIFICATION (user, contact);
