CREATE TABLE SUBSCRIPTIONS(id VARCHAR(64) PRIMARY KEY, user VARCHAR(1023) NOT NULL, contact VARCHAR(2047) NOT NULL, name VARCHAR(128), state VARCHAR(20) NOT NULL, groups VARCHAR(2000));
CREATE INDEX INDEX_SUBSCRIPTIONS_NAME ON SUBSCRIPTIONS (name);
CREATE UNIQUE INDEX UNIQUE_INDEX_SUBSCRIPTIONS_NAME_CONTACT ON SUBSCRIPTIONS (name, contact);

CREATE TABLE SUBSCRIPTION_NOTIFICATIONS (id VARCHAR(64) PRIMARY KEY, notification_id VARCHAR(64) UNIQUE NOT NULL, user VARCHAR(1023) NOT NULL, contact VARCHAR(2047) NOT NULL, subscription_type VARCHAR(12) NOT NULL, additional_message VARCHAR(128), CONSTRAINT UNIQUE_USER_CONTACT_SUBSCRIPTION_TYPE UNIQUE (user, contact, subscription_type));
CREATE INDEX INDEX_SUBSCRIPTION_NOTIFICATIONS_USER_CONTACT ON SUBSCRIPTION_NOTIFICATIONS (user, contact);

CREATE TABLE TRACEABLE_MESSAGES(id VARCHAR(64) PRIMARY KEY, jid VARCHAR(1023) NOT NULL, message_id VARCHAR(64) NOT NULL, message VARCHAR(16384) NOT NULL, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX INDEX_TRACEABLE_MESSAGES_JID ON TRACEABLE_MESSAGES (jid);
CREATE UNIQUE INDEX UNIQUE_INDEX_TRACEABLE_MESSAGES_JID_MESSAGE_ID ON TRACEABLE_MESSAGES (jid, message_id);

CREATE TABLE MSG_TRACES(id VARCHAR(64) PRIMARY KEY, jid VARCHAR(1023) NOT NULL, message_id VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, from_jid VARCHAR(1023) NOT NULL, stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX INDEX_MSG_TRACES_JID ON MSG_TRACES (jid);
CREATE INDEX INDEX_MSG_TRACES_JID_MESSAGE_ID ON MSG_TRACES (jid, message_id);