CREATE TABLE OFFLINE_MESSAGE(id VARCHAR(64) PRIMARY KEY, message_id VARCHAR(64) NOT NULL, message VARCHAR(16384) NOT NULL, jid VARCHAR(2047) NOT NULL, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX UNIQUE_INDEX_OFFLINE_MESSAGE_MESSAGE_ID ON OFFLINE_MESSAGE (message_id);
CREATE INIDX INDEX_OFFLINE_MESSAGE_JID OFFLINE_MESSAGE (jid);
